server:
  port: 8003
logging:
  level:
    web: debug
    com.xymiao.cms: debug
    com.xymiao.cms.config: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/mzcms?useUnicode=true&useSSL=true
    username: mzcms
    password: mzcms
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password: admin.com
      timeout: 3000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
