server:
  port: 8090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/mzcms?useUnicode=true&useSSL=true
    username: mzcms
    password: mzcms
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
